FPTBookStore/Controllers/AdminController.cs
using FPTBookStore.Data;
using FPTBookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;

namespace FPTBookStore.Controllers
{

    public class AdminController : Controller
    {
        private readonly ApplicationDbContext context;
        public AdminController(ApplicationDbContext dbContext)
        {
            context = dbContext;

        }
        [Authorize(Roles = "Administrator")]
        [Route("/Admin")]
        public IActionResult Index()
        {
            var categories = context.WaitCategory.ToList();
            ViewBag.Checks = categories.Count;
            return View(categories);
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Approve(int? id)
        {
            var categories = context.WaitCategory.ToList();
            var item = categories.Find(p => p.Id == id);


            var categories2 = context.Category.ToList();
            var item2 = categories2.Find(p => p.Name == item.Name);

            item2.Status = "Active";

            context.Category.Update(item2);

            context.WaitCategory.Remove(item);

            context.SaveChanges();
            return Redirect("/Admin");
        }
        [Authorize(Roles = "Owner")]
        public IActionResult ListOrder()
        {
            var orders = context.Order.ToList();
            ViewBag.Users = context.Users.ToList();
            ViewBag.products = context.Product.ToList();
            return View(orders);
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Reject(int? id)
        {
            var categories = context.WaitCategory.ToList();
            var item = categories.Find(p => p.Id == id);

            var categories2 = context.Category.ToList();
            var item2 = categories2.Find(p => p.Name == item.Name);

            item2.Status = "Reject";

            context.Category.Update(item2);

            context.WaitCategory.Remove(item);

            context.SaveChanges();
            return Redirect("/Admin");
        }

        //Below are actions to reset password

        [Authorize(Roles = "Administrator")]
        public IActionResult Reset()
        {
            // select user by roles
            var users = context.Users.ToList();
            var roles = context.Roles.ToList();
            ViewBag.Roles = roles;
            return View(users);
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(string? id)
        {
            var users = context.Users.ToList();
            var user = users.Find(p => p.Id == id);
            return View(user);
        }

        [Authorize(Roles = "Administrator")]

        [HttpPost]
        public IActionResult Update()
        {
            string id = Request.Form["id"];
            string old_pass = Request.Form["oldpass"];
            string new_pass = Request.Form["newpass"];
            string confirm_pass = Request.Form["confirmpass"];

            ViewData["OldPass"] = old_pass;
            ViewData["NewPass"] = new_pass;
            ViewData["ConfirmPass"] = confirm_pass;

            var list_users = context.Users.ToList();
            var user = list_users.Find(p => p.Id == id);

            var passwordHasher = new PasswordHasher<ApplicationUser>();

            var temp_user = new ApplicationUser
            {
                Id = id,
                UserName = user.UserName,
                Email = user.Email,
                PasswordHash = user.PasswordHash,
            };

            var result = passwordHasher.VerifyHashedPassword(temp_user, user.PasswordHash, old_pass);

            if (result == PasswordVerificationResult.Success)
            {
                if (new_pass == confirm_pass)
                {
                    TempData["Message"] = "Update password successfully!";
                    var new_hash = passwordHasher.HashPassword(temp_user, new_pass);
                    user.PasswordHash = new_hash;
                    context.Users.Update(user);
                    context.SaveChanges();
                    return Redirect("/Admin/Reset");
                }
                else
                {
                    ViewBag.Error1 = "Confirm password is not match";
                    return View("Edit", user);
                }
            }
            else
            {
                ViewBag.Error2 = "Old password is not match";
                return View("Edit", user);
            }

        }

    }
}

FPTBookStore/Controllers/CustomerController.cs
using FPTBookStore.Models;
using FPTBookStore.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Security.Claims;
using Newtonsoft.Json;

namespace FPTBookStore.Controllers
{
    public class CustomerController : Controller
    {

        public const string CARTKEY = "cart";
        List<CartItem> GetCartItems()
        {
            var session = HttpContext.Session;
            string jsoncart = session.GetString(CARTKEY);
            if (jsoncart != null)
            {
                return JsonConvert.DeserializeObject<List<CartItem>>(jsoncart);
            }
            return new List<CartItem>();
        }

        // Xóa cart khỏi session
        void ClearCart()
        {
            var session = HttpContext.Session;
            session.Remove(CARTKEY);
        }

        // Lưu Cart (Danh sách CartItem) vào session
        void SaveCartSession(List<CartItem> ls)
        {
            var session = HttpContext.Session;
            string jsoncart = JsonConvert.SerializeObject(ls);
            session.SetString(CARTKEY, jsoncart);
        }
        private readonly ApplicationDbContext context;
        public CustomerController(ApplicationDbContext dbContext)
        {
            context = dbContext;

        }
        [Route("/")]
        public IActionResult Index()
        {
            var products = context.Product.ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(products);
        }


        public IActionResult Index2(int? id)
        {
            var products = context.Product.ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            var productSearch = context.Category.Include(c => c.Products).FirstOrDefault(c => c.Id == id);
            return View(productSearch);
        }
        [HttpPost]
        public IActionResult Search(string search)
        {
            var products = context.Product.Where(p => p.Name.Contains(search)).ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            TempData["search"] = search;

            return View("Index", products);
        }
        public IActionResult Details(int? id)
        {
            var products = context.Product.ToList();
            var item = products.FirstOrDefault(c => c.Id == id);
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(item);
        }

        [Authorize(Roles = "Customer,Administrator")]
        public IActionResult AddtoCart(int? id)
        {
            var product = context.Product
        .Where(p => p.Id == id)
        .FirstOrDefault();
            if (product == null)
                return NotFound("Không có sản phẩm");

            // Xử lý đưa vào Cart ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.Id == id);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.Quantity++;
            }
            else
            {
                //  Thêm mới
                cart.Add(new CartItem() { Quantity = 1, product = product });
            }

            // Lưu cart vào Session
            SaveCartSession(cart);
            // Chuyển đến trang hiện thị Cart
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ViewCart()
        {
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(GetCartItems());
        }

        [Route("/updatecart", Name = "updatecart")]
        [HttpPost]
        public IActionResult UpdateCart(int productid, int quantity)
        {
            // Cập nhật Cart thay đổi số lượng quantity ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.Id == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.Quantity = quantity;
            }
            SaveCartSession(cart);
            // Trả về mã thành công (không có nội dung gì - chỉ để Ajax gọi)
            return Ok();
        }
        [Route("/removecart/{productid:int}", Name = "removecart")]
        public IActionResult RemoveCart([FromRoute] int productid)
        {
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.Id == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cart.Remove(cartitem);
            }

            SaveCartSession(cart);
            return RedirectToAction(nameof(ViewCart));
        }
        public IActionResult UserView()
        {
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            var claimIdentity = (ClaimsIdentity)User.Identity;

            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = claims.Value;
            //var user = _context.Users.OfType<ApplicationUser>().FirstOrDefault(u => u.UserName == userName);
            ApplicationUser currentUser = (ApplicationUser)context.Users.FirstOrDefault(x => x.Id == currentUserId);

            ViewBag.Img = currentUser.Image;
            ViewBag.Id = currentUser.Id;
            ViewBag.Email = currentUser.Email;
            ViewBag.UserName = currentUser.UserName;
            ViewBag.Fullname = currentUser.FullName;
            ViewBag.Address = currentUser.Address;
            ViewBag.Dob = currentUser.DoB;
            return View();
        }
        public IActionResult Checkout()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = claims.Value;

            // caculate total price
            var cart = GetCartItems();
            double total = 0;
            foreach (var item in cart)
            {
                total += (double)(item.product.Price * item.Quantity);
            }

            for (int i = 0; i < cart.Count; i++)
            {
                var order = new Order()
                {
                    UserId = currentUserId,
                    ProductId = cart[i].product.Id,
                    ProductName = cart[i].product.Name,
                    image = cart[i].product.Image,
                    Price = (int)cart[i].product.Price,
                    Quantity = cart[i].Quantity,
                    TotalPrice = total,

                };
                context.Order.Add(order);
                context.SaveChanges();
            }
            ClearCart();
            return RedirectToAction(nameof(Index));

        }
        public IActionResult ViewOrder()
        {
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = claims.Value;
            //int UsrID = Int32.Parse(currentUserId);
            string UsrID = currentUserId;
            var orders = context.Order.ToList();
            var FindOrder = context.Order.Where(p => p.UserId.Contains(currentUserId)).ToList();
            return View("ViewOrder", FindOrder);

        }
    }

}

FPTBookStore/Views/Admin/CartConfirm.cshtml
@model List<FPTBookStore.Models.CartItem>
<table class="table">
    <tr>
        <th>#</th>
        <th>Sản phẩm</th>
        <th>Giá</th>
        <th>Số lượng</th>
        <th>Thành tiền</th>
        <th></th>
    </tr>
    @foreach (var cartitem in Model)
    {
        var thanhtien = cartitem.Quantity * cartitem.product.Price;
        

        <tr>
            <td>@cartitem.product.Name</td>
            <td>@(cartitem.product.Price.ToString("n0"))</td>
            <td><input asp-for="@cartitem.Quantity" id="@($"quantity-{cartitem.product.Id}")" readonly="readonly" /></td>
            <td>@(thanhtien.ToString("n0"))</td>
        </tr>
    }
    <tr>
        
    </tr>
</table>
<a asp-controller="Customer" asp-action="ClearCart">Reject</a>
<a asp-controller="Admin" asp-action="Accept">Accept</a>

FPTBookStore/Views/Admin/Edit.cshtml
@model FPTBookStore.Models.ApplicationUser
@{
    ViewData["Title"] = "Update";
}
@if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
{
    <h1 style="text-align: center">Reset password</h1>

    <h4>FPT BOOK </h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-controller="Admin" asp-action="Update" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    @*<label type = "hidden" asp-for="Id" class="control-label"></label>*@
                    <input type="hidden" asp-for="Id" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="FullName" readonly class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="UserName" readonly class="control-label"></label>
                    <input asp-for="UserName" readonly class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" readonly class="control-label"></label>
                    <input asp-for="Email" readonly class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label">Old Password</label>
                    <input name="oldpass" type="password" value="@ViewData["OldPass"]" class="form-control" />
                    <span class="text-danger">@ViewBag.Error2</span>
                    @*ViewBag.Error2 = "Old password is not match";*@
                </div>

                <div class="form-group">
                    <label class="control-label">New Password</label>
                    <input asp-for="PasswordHash" type="password" value="@ViewData["NewPass"]" name="newpass" class="form-control" />
                </div>


                <div class="form-group">
                    <label class="control-label">Confirm Password</label>
                    <input asp-for="PasswordHash" type="password" value="@ViewData["ConfirmPass"]" name="confirmpass" class="form-control" />
                    <span class="text-danger">@ViewBag.Error1</span>
                    @*ViewBag.Error1 = "Confirm password is not match";*@
                </div>

                <div>
                    <br>
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <br>
    <div>
        <a asp-controller="Admin" asp-action="Reset">Back to List</a>
    </div>
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

    @*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

FPTBookStore/Views/Admin/Index.cshtml
@model List<WaitCategory>

@{
    ViewData["Title"] = "Index";
}

<h1>Manage category request</h1>
@if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
{
    @if (Model.Count == 0)
    {
        <center style="font-size: 80px">
            <span class="badge badge-danger">No Request for create new category!!!!!</span>
        </center>
    }
    else
    {
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        Category ID
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Id

                        </td>
                        <td>
                            @item.Name
                        </td>

                        <td>
                            @item.Description
                        </td>

                        @if (item.Status == "Pending")
                        {
                            <td>

                                <span class="badge badge-warning">@item.Status</span>

                            </td>
                        }
                        else if (item.Status == "Active")
                        {
                            <td>

                                <span class="badge badge-primary">@item.Status</span>

                            </td>
                        }
                        else
                        {
                            <td>

                                <span class="badge badge-danger">@item.Status</span>

                            </td>
                        }
                        <td>
                            <a asp-controller="Admin" asp-action="Approve" asp-route-id="@item.Id" class="btn btn-primary">Approve</a>
                        </td>

                        <td>
                            <a asp-controller="Admin" asp-action="Reject" asp-route-id="@item.Id" class="btn btn-dark">Reject</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

}

FPTBookStore/Views/Admin/ListOrder.cshtml
@model List<Order>


@{
    ViewData["Title"] = "Index";
}

<h1>Manage order request</h1>
@if (User.Identity.IsAuthenticated && User.IsInRole("Owner"))
{
    @if (Model.Count == 0)
    {
        <center>
            <span class="badge badge-danger">Do not have any order</span>
        </center>

    }
    else
    {
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        Order ID
                    </th>
                    <th>
                        Email User
                    </th>
                    <th>
                        Product Name
                    </th>
                    <th>
                        Quantity
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                       Total Price
                    </th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Id

                        </td>
                        <td>
                            @for (int i = 0; i < ViewBag.Users.Count; i++)
                            {
                                if (ViewBag.Users[i].Id == item.UserId)
                                {
                                    <text>@ViewBag.Users[i].Email </text>
                                }
                            }
                        </td>

                        <td>
                            @for (int i = 0; i < ViewBag.Products.Count; i++)
                            {
                                if (ViewBag.Products[i].Id == item.ProductId)
                                {
                                    <text>@ViewBag.Products[i].Name </text>
                                }
                            }
                        </td>
                        <td>
                            @item.Quantity
                        </td>
                        <td>
                            @item.Price
                        </td>
                        <td>
                            @item.TotalPrice
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

FPTBookStore/Views/Admin/Reset.cshtml
@{
    ViewData["Title"] = "Reset password";
}

<h1 style="color: black;text-align: center">
    Reset password
</h1>
    @if (TempData["Message"] != null)
    {
        <center style="font-size: 200%;">
            <span class="badge badge-danger" >@TempData["Message"]</span>
    </center>
    }
    else
    {
        <p></p>
    }
    <h2>Wellcome to Admin Dasboard!</h2>
@if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
{
    <table class="table table-hover">
        <thead>
        <tr style="background-color: chartreuse">
                <th>
                    ID
                </th>

                <th>
                    Email
                </th>
                <th>
                    UserName
                </th>
                <th>
                    Password
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.UserName
                    </td>

                    <td>
                        *********
                    </td>
                    @for (int i = 0; i < ViewBag.Roles.Count; i++)
                    {
                        if (ViewBag.Roles[i].Id == "O")
                        {
                            <td>
                                <a asp-controller="Admin" asp-action="Edit" class="action-icon" asp-route-id="@item.Id"> <i class="mdi mdi-square-edit-outline "></i></a>
                            </td>

                        }
                    }

                </tr>
            }

        </tbody>
    </table>
}