FPTBookStore/Controllers/AdminController.cs
using FPTBookStore.Data;
using FPTBookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;

namespace FPTBookStore.Controllers
{

    public class AdminController : Controller
    {
        private readonly ApplicationDbContext context;
        public AdminController(ApplicationDbContext dbContext)
        {
            context = dbContext;

        }
        [Authorize(Roles = "Administrator")]
        [Route("/Admin")]
        public IActionResult Index()
        {
            var categories = context.WaitCategory.ToList();
            ViewBag.Checks = categories.Count;
            return View(categories);
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Approve(int? id)
        {
            var categories = context.WaitCategory.ToList();
            var item = categories.Find(p => p.Id == id);


            var categories2 = context.Category.ToList();
            var item2 = categories2.Find(p => p.Name == item.Name);

            item2.Status = "Active";

            context.Category.Update(item2);

            context.WaitCategory.Remove(item);

            context.SaveChanges();
            return Redirect("/Admin");
        }
        [Authorize(Roles = "Owner")]
        public IActionResult ListOrder()
        {
            var orders = context.Order.ToList();
            ViewBag.Users = context.Users.ToList();
            ViewBag.products = context.Product.ToList();
            return View(orders);
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Reject(int? id)
        {
            var categories = context.WaitCategory.ToList();
            var item = categories.Find(p => p.Id == id);

            var categories2 = context.Category.ToList();
            var item2 = categories2.Find(p => p.Name == item.Name);

            item2.Status = "Reject";

            context.Category.Update(item2);

            context.WaitCategory.Remove(item);

            context.SaveChanges();
            return Redirect("/Admin");
        }

        //Below are actions to reset password

        [Authorize(Roles = "Administrator")]
        public IActionResult Reset()
        {
            // select user by roles
            var users = context.Users.ToList();
            var roles = context.Roles.ToList();
            ViewBag.Roles = roles;
            return View(users);
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(string? id)
        {
            var users = context.Users.ToList();
            var user = users.Find(p => p.Id == id);
            return View(user);
        }

        [Authorize(Roles = "Administrator")]

        [HttpPost]
        public IActionResult Update()
        {
            string id = Request.Form["id"];
            string old_pass = Request.Form["oldpass"];
            string new_pass = Request.Form["newpass"];
            string confirm_pass = Request.Form["confirmpass"];

            ViewData["OldPass"] = old_pass;
            ViewData["NewPass"] = new_pass;
            ViewData["ConfirmPass"] = confirm_pass;

            var list_users = context.Users.ToList();
            var user = list_users.Find(p => p.Id == id);

            var passwordHasher = new PasswordHasher<ApplicationUser>();

            var temp_user = new ApplicationUser
            {
                Id = id,
                UserName = user.UserName,
                Email = user.Email,
                PasswordHash = user.PasswordHash,
            };

            var result = passwordHasher.VerifyHashedPassword(temp_user, user.PasswordHash, old_pass);

            if (result == PasswordVerificationResult.Success)
            {
                if (new_pass == confirm_pass)
                {
                    TempData["Message"] = "Update password successfully!";
                    var new_hash = passwordHasher.HashPassword(temp_user, new_pass);
                    user.PasswordHash = new_hash;
                    context.Users.Update(user);
                    context.SaveChanges();
                    return Redirect("/Admin/Reset");
                }
                else
                {
                    ViewBag.Error1 = "Confirm password is not match";
                    return View("Edit", user);
                }
            }
            else
            {
                ViewBag.Error2 = "Old password is not match";
                return View("Edit", user);
            }

        }

    }
}

FPTBookStore/Controllers/CategoryController.cs
using FPTBookStore.Data;
using FPTBookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;
using System.Linq;

namespace FPTBookStore.Controllers
{

    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext context;
        public CategoryController(ApplicationDbContext dbContext)
        {
            context = dbContext;

        }
        [Authorize(Roles = "Owner")]
        public IActionResult Index()
        {
            var categories = context.Category.ToList();


            return View(categories);


        }
        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Create(WaitCategory category)
        {
            if (ModelState.IsValid)
            {
                var newCategory = new WaitCategory
                {
                    Name = category.Name,
                    Description = category.Description,
                    Status = "Pending"
                };
                var newCategory2 = new Category
                {
                    Name = category.Name,
                    Description = category.Description,
                    Status = "Pending"
                };
                context.Category.Add(newCategory2);
                context.WaitCategory.Add(newCategory);
                context.SaveChanges();
                return Redirect("/Category");
            }
            return View();
        }

        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Details(int? id)
        {
            var categories = context.Category.ToList();
            var item = categories.Find(p => p.Id == id);
            return View(item);
        }

        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var categories = context.Category.ToList();
            var item = categories.Find(p => p.Id == id);



            return View(item);
        }

        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Update(Category category)
        {
            if (ModelState.IsValid)
            {
                context.Category.Update(category);
                context.SaveChanges();
                return Redirect("/Category");
            }
            return View();
        }

        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Confirm(int? id)
        {
            var categories = context.Category.ToList();
            var item = categories.Find(p => p.Id == id);
            return View(item);
        }

        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Delete(Category category)
        {

            var categories = context.WaitCategory.ToList();
            var item = categories.Find(p => p.Name == category.Name);

            if (item != null)
            {
                context.WaitCategory.Remove(item);
            }
            context.Category.Remove(category);

            context.SaveChanges();
            return Redirect("/Category");

        }

    }
}

FPTBookStore/Controllers/ProductController.cs
using FPTBookStore.Data;
using FPTBookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;


namespace FPTBookStore.Controllers
{


    public class ProductsController : Controller
    {

        private readonly ApplicationDbContext context;


        public ProductsController(ApplicationDbContext dbContext)
        {
            context = dbContext;

        }
        protected UserManager<ApplicationUser> UserManager { get; set; }



        [Authorize(Roles = "Owner")]
        public IActionResult Index()
        {
            var products = context.Product.ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(products);
            //ViewData["CategoryId"] = new SelectList(context.Set<Category>(), "Id", "Id");
            //return View();
        }

        [Authorize(Roles = "Owner")]
        [HttpGet]

        public IActionResult Create()
        {
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            //if (categories == null)
            //{
            //    Console.WriteLine("Error");
            //}
            //else
            //{
            //    ViewBag.Categories = categories;
            //}
            return View();
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                TempData["Message"] = "Create product successfully";
                context.Product.Add(product);
                context.SaveChanges();
                return Redirect("/products");
            }
            return View();
        }
        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Details(int? id)
        {
            var products = context.Product.ToList();
            var item = products.Find(p => p.Id == id);
            return View(item);
        }
        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var products = context.Product.ToList();
            var item = products.Find(p => p.Id == id);
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View(item);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Update(Product product)
        {
            if (ModelState.IsValid)
            {
                TempData["Message"] = "Update product successfully";
                context.Product.Update(product);
                context.SaveChanges();
                return Redirect("/products");

            }
            return View();
        }
        [Authorize(Roles = "Owner")]
        [HttpGet]
        public IActionResult Confirm(int? id)
        {
            var products = context.Product.ToList();
            var item = products.Find(p => p.Id == id);
            return View(item);
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Delete(Product product)
        {
            TempData["Message"] = "Delete product successfully";
            context.Product.Remove(product);
            context.SaveChanges();
            return Redirect("/products");
        }

        public IActionResult UserView()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;

            var claims = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = claims.Value;
            ApplicationUser currentUser = (ApplicationUser)context.Users.FirstOrDefault(x => x.Id == currentUserId);

            ViewBag.Img = currentUser.Image;
            ViewBag.Id = currentUser.Id;
            ViewBag.Email = currentUser.Email;
            ViewBag.UserName = currentUser.UserName;
            ViewBag.Fullname = currentUser.FullName;
            ViewBag.Address = currentUser.Address;
            ViewBag.Dob = currentUser.DoB;
            return View(currentUser);
        }

        [HttpPost]
        public IActionResult Search(string search)
        {
            var products = context.Product.Where(p => p.Name.Contains(search)).ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            
            return View("Index", products);
        }
        public IActionResult SortDESC()
        {
            var products = context.Product.OrderByDescending(p => p.Quantity).ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View("Index", products);
        }
        public IActionResult SortASC()
        {
            var products = context.Product.OrderBy(p => p.Quantity).ToList();
            var categories = context.Category.ToList();
            ViewBag.Categories = categories;
            return View("Index", products);
        }
    }


}

FPTBookStore/Views/Shared/_ErrorLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Error 404 | ACCESS DENIED </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">

    <!-- App css -->
    <link href="~/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/app.min.css" rel="stylesheet" type="text/css" id="light-style" />
    <link href="assets/css/app-dark.min.css" rel="stylesheet" type="text/css" id="dark-style" />

</head>

<body class="loading" data-layout-config='{"leftSideBarTheme":"dark","layoutBoxed":false, "leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}' style="background: url('@Url.Content("~/images/whale.jpg")')">

    @RenderBody()
    <!-- end page -->

    <footer class="footer footer-alt">
        2023-2024 | FPTBook By HMN | Road to Future 
    </footer>

    <!-- bundle -->
    <script src="~/js/vendor.min.js"></script>
    <script src="~/js/app.min.js"></script>

</body>
</html>

FPTBookStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>FPTBook Store Owner Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/images/favicon.ico">

    <!-- App css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />
    <link href="~/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/app.min.css" rel="stylesheet" type="text/css" id="light-style" />
    <link href="~/css/app-dark.min.css" rel="stylesheet" type="text/css" id="dark-style" />
    <link href="~/css/BookOwner.css" rel="stylesheet" type="text/css" />

</head>

<body class="loading" data-layout-config='{"leftSideBarTheme":"dark","layoutBoxed":false, "leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}'>
    <!-- Begin page -->
    <div class="wrapper">
        <!-- ========== Left Sidebar Start ========== -->
        <div class="left-side-menu">
            <!-- LOGO -->
            <a asp-controller="Products" asp-action="Index" class="logo text-center logo-light">
                <a class="logo text-center logo-light" asp-controller="Products" asp-action="Index">
                    @*Left*@
                    <span class="logo-lg">
                        <img src="~/img/mainlogo.png" alt="LogoFPTBook" height="50" class="rounded-circle">
                    </span>
                    @*Right*@
                    <span class="logo-sm">
                        nav-link dropdown-toggle nav-user arrow-none mr-0
                        <img src="~/img/mainlogo.png" alt="LogoFPTBook" height="16" class="rounded-circle">
                    </span>
                </a>
            </a>

            <!-- LOGO -->
            <a asp-controller="Products" asp-action="Index" class="logo text-center logo-dark">
                <span class="logo-lg">
                    <img src="~/images/logo-dark.png" alt="" height="16">
                </span>
                <span class="logo-sm">
                    <img src="~/images/logo_sm_dark.png" alt="" height="16">
                </span>
            </a>

            <div class="h-100" id="left-side-menu-container" data-simplebar>
                <!--- Sidemenu -->
                <ul class="metismenu side-nav">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Owner"))
                    {
                        <li class="side-nav-title side-nav-item">Store Owner Manager</li>
                        <li class="side-nav-item">
                            <a asp-controller="Products" asp-action="Index" class="side-nav-link">
                                <i class="uil-home-alt"></i>
                                <span> Products </span>
                            </a>
                        </li>

                        <li class="side-nav-title side-nav-item"> </li>
                        <li class="side-nav-item">
                            <a asp-controller="Category" asp-action="Index" class="side-nav-link">
                                <i class="uil-calender"></i>
                                <span> Category </span>
                            </a>
                        </li>
                        <li class="side-nav-title side-nav-item"> </li>
                        <li class="side-nav-item">
                            <a asp-controller="Admin" asp-action="ListOrder" class="side-nav-link">
                                <i class="uil-align-justify"></i>
                                <span> List order </span>
                            </a>
                        </li>
                    }

                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                    {
                        <li class="side-nav-item">
                            <a asp-controller="Admin" asp-action="Index" class="side-nav-link">
                                <i class="uil-calender"></i>
                                <span> Manager Category</span>
                            </a>
                        </li>
                        <li class="side-nav-item">
                            <a asp-controller="Admin" asp-action="Reset" class="side-nav-link">
                                <i class="uil-calender"></i>
                                <span> Reset Password </span>
                            </a>
                        </li>
                    }



                </ul>
            </div>
            <!-- Sidebar -left -->

        </div>
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start Page Content here -->
        <!-- ============================================================== -->

        <div class="content-page" style="background-color: antiquewhite">
            <div class="content">
                <!-- Topbar Start -->
                <div class="navbar-custom" style="background-color: wheat">
                    <ul class="list-unstyled topbar-right-menu float-right mb-0">
                        @*Search *@
                        <li class="dropdown notification-list d-lg-none">
                            <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                <i class="dripicons-search noti-icon"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-animated dropdown-lg p-0">
                                <form class="p-3">
                                    <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                </form>
                            </div>
                        </li>

                        @*Right NAV*@
                        <li class="dropdown notification-list" style="background-color: wheat; color: red">
                            <a class="nav-link dropdown-toggle nav-user arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false"
                               aria-expanded="false" style="background-color: wheat">
                                <span class="account-user-avatar">
                                    <img src="~/img/mainlogo.png" alt="user-image" class="rounded-circle">
                                </span>
                                <span class="btn btn-success">
                                    <span class="account-user-name">FPTBook Store Owner</span>
                                    @*<span class="account-position"></span>*@
                                </span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
                                @if (SignInManager.IsSignedIn(User))
                                {
                                <!-- item-->
                                <div class=" dropdown-header noti-title">
                                    <h6 class="text-overflow m-0">Welcome to System!</h6>
                                </div>

                                <!-- item-->
                                <a asp-controller="Products" asp-action="UserView" class="dropdown-item notify-item">
                                    <i class="mdi mdi-account-circle mr-1"></i>
                                    <span>My Account</span>
                                </a>

                                <!-- item-->
                               

                                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                        <button type="submit" class="dropdown-item notify-item"> <i class="mdi mdi-logout mr-1"></i>Logout</button>
                                    </form>
                                }
                            </div>
                        </li>

                    </ul>
                    <button class="button-menu-mobile open-left disable-btn">
                        <i class="mdi mdi-menu"></i>
                    </button>
                    <div class="app-search dropdown d-none d-lg-block">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Owner"))
                        {
                            <form asp-controller="Products" asp-action="Search" method="post">
                                <div class="input-group">
                                    <input type="text" class="form-control dropdown-toggle" placeholder="Search..." name="Search"  id="top-search" style="border-radius:25px">
                                    <span class="mdi mdi-magnify search-icon"></span>
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit" style="border-radius:25px; margin-left:10px">Search</button>
                                    </div>
                                </div>
                            </form>
                        }

                    </div>
                </div>
                <!-- end Topbar -->
                <!-- Start Content-->
                <div class="container-fluid" style="margin-bottom: 10px">
                    @RenderBody()

                </div> <!-- container -->

            </div> <!-- content -->
            <!-- Footer Start -->
            <footer class="footer" style="background-color: darkblue">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6" >
                            2023 © FPT BOOK STORE BY HUY, MINH, NGHIA | COPPY RIGHT
                        </div>
                    </div>
                </div>
            </footer>
            <!-- end Footer -->

        </div>

        <!-- ============================================================== -->
        <!-- End Page content -->
        <!-- ============================================================== -->


    </div>
    <!-- END wrapper -->
    <!-- Right Sidebar -->
    <!-- /Right-bar -->
    <!-- bundle -->
    <script src="~/js/vendor.min.js"></script>
    <script src="~/js/app.min.js"></script>
    @*<script src="~/Template/js/jquery.min.js"></script>
    <script src="~/Template/js/popper.min.js"></script>
    <script src="~/Template/js/bootstrap.bundle.min.js"></script>
    <script src="~/Template/js/jquery-3.0.0.min.js"></script>
    <script src="~/Template/js/plugin.js"></script>
    <!-- sidebar -->
    <script src="~/Template/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/Template/js/custom.js"></script>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>*@

    @RenderSection("Scripts", required: false)
</body>
</html>

FPTBookStore/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>FPT Book</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">

    <!-- App css -->
    <link href="~/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/app.min.css" rel="stylesheet" type="text/css" id="light-style" />
    <link href="~/css/app-dark.min.css" rel="stylesheet" type="text/css" id="dark-style" />

</head>

<body class="authentication-bg pb-0" data-layout-config='{"darkMode":false}' style="background: url('@Url.Content("~/images/whale.jpg")')">

    <div class="auth-fluid" >
        <!--Auth fluid left content -->
        @RenderBody()
        <!-- end auth-fluid-form-box-->
        <!-- Auth fluid right content -->
        <div class="auth-fluid-right text-center">
            <div class="auth-user-testimonial">
                <h2 class="mb-3">I love books!</h2>
                <p class="lead">
                    <i class="mdi mdi-format-quote-open"></i> Reading book is opening new world <i class="mdi mdi-format-quote-close"></i>
                </p>
                <p>
                    - FPT Book
                </p>
            </div> <!-- end auth-user-testimonial-->
        </div>
        <!-- end Auth fluid right content -->
    </div>
    <!-- end auth-fluid-->
    <!-- bundle -->
    <script src="~/js/vendor.min.js"></script>
    <script src="~/js/app.min.js"></script>
    <script type="text/javascript">


        function disableBackButton() {
            window.history.forward();
        }
        setTimeout("disableBackButton()", 0);
    </script>

    @RenderSection("Scripts", required: false)
</body>

</html>